name: avenir
favicon: null
layout_spectrum: 0.98016
typography_spectrum: 1
title: A light in a dark place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e1dd'
    - '#000000'
    - '#5cbecb'
    - '#e59ad2'
    - '#d40c4b'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
